### ISSUE TITLE
Small issues with spamassassin and clamav

### ISSUE THREAD

**Issue by dengste** [larsmagne/make-mta#1]
Hey Lars,

thanks so much for documenting your setup with this script. This was very helpful in migrating my old mail setup to a new server.

I didn't actually run the script because my setup is a bit different, but I've followed most of the commands. A few smaller issues:

- Using your 35_stop_spam exim conf-File did not work because these options need to be in the acl_check_data block. I activated the corresponding lines in 40_exim4-config_check_data instead and this did the job.

- You need to enable the spamasassin.service or it will not run after a reboot:

        systemctl enable spamassassin.service

- Clamav needs to be able to access /var/spool/exim4/scan, so you need to do

       adduser clamav Debian-exim

- After installing fail2ban you also need to activate some of the jails otherwise it won't do anything. Copy /etc/fail2ban/jails.conf to /etc/fail2ban/jails.local and put 'enabled=true' in sections [sshd], [exim] and [dovecot].

**Comment by larsmagne** [comment]
Hi,

thanks for the fixes -- I've now amended the script.

Moving 35_stop_spam til 45_stop_spam should do the trick?

As for fail2ban, it seems to work for me without doing anything more than the script does -- at least it gives me lines like:

2020-04-30 02:30:30,817 fail2ban.actions        [915]: NOTICE  [sshd] Ban 193.93.12.122
2020-04-30 02:40:31,651 fail2ban.actions        [915]: NOTICE  [sshd] Unban 193.93.12.122

Hm...  but I guess that doesn't cover exim and dovecot by default, so I'll make the adjustments you suggest.

**Comment by dengste** [comment]
The last entry in 40_exim4-config_check_data is a final 'accept', so if you go behind that I don't think this works, but I'm not sure. Exim configuration really has become the new Sendmail.

It might be that fail2ban does ssh by default. I always move my ssh port so I don't see anything there anyway. But enabling it for Exim definitely makes sense, I would also recommend to use 'mode=aggressive' to get rid of all the bots that scan the mail ports. 

BTW, did you look at https://mailinabox.email ?

**Comment by larsmagne** [comment]
Thanks; I missed that.  I've now amended the script to remove the "accept" from the 40* file and put it in a separate file, so that the SpamAssassin/clamav stuff can live in a file of its own.  *sigh*

I think I'll leave "aggressive" up to the user...  I just wanted a script that would do only what's necessary, without being too opinionated.

mailinabox looks nice, but it too tied to cloud infrastructure for my liking.
