### ISSUE TITLE
Support SMTP via Tor out of the box?

### ISSUE THREAD

**Issue by petterreinholdtsen** [larsmagne/make-mta#3]
What about supporting email sending and receiving over Tor, as described on
http://people.skolelinux.org/pere/blog/A_Debian_package_for_SMTP_via_Tor__aka_SMTorP__using_exim4.html ?  It would make it possible to send and receive email using .onion addresses and send emails to and from the machines without leaking information about where the server is.

**Comment by larsmagne** [comment]
Well, the script is meant as a bare-bones setup of what's required to run an SMTP server (and have Gmail accept your emails).  Any features beyond that are not part of the remit.

**Comment by petterreinholdtsen** [comment]
[Lars Ingebrigtsen]
> Well, the script is meant as a bare-bones setup of what's required to
> run an SMTP server (and have Gmail accept your emails).  Any features
> beyond that are not part of the remit.

OK, no worries.  It just occured to me that it could be a nice addition
for reducing the information leak. :)

-- 
Happy hacking
Petter Reinholdtsen
